# Generated by Django 2.0.2 on 2018-03-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitparticipant_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitparticipant',
            name='accepted',
            field=models.NullBooleanField(help_text='Cocher si les pièces jointes envoyées sont valides.', verbose_name='dossier validé'),
        ),
        migrations.AlterField(
            model_name='visitparticipant',
            name='present',
            field=models.NullBooleanField(help_text='Une fois la sortie passée, indiquer si le lycéen était présent.', verbose_name='présent'),
        ),
    ]
