# Generated by Django 2.0.2 on 2018-03-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20180302_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitAttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('file', models.FileField(upload_to='', verbose_name='fichier')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='visits.Visit')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ('visit',),
            },
        ),
    ]
