# Generated by Django 2.0.2 on 2018-03-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_visitattachedfile_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitattachedfile',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='visits.Visit', verbose_name='sortie'),
        ),
    ]
