# Generated by Django 2.0.4 on 2018-05-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_auto_20180319_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitAttachedFile',
            new_name='AttachedFile',
        ),
    ]
