# Generated by Django 2.0.4 on 2018-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180512_1344'),
        ('visits', '0009_auto_20180520_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='organizers_group',
        ),
        migrations.AddField(
            model_name='visit',
            name='organizers',
            field=models.ManyToManyField(related_name='organized_visits', to='profiles.Tutor'),
        ),
    ]
