# Generated by Django 2.0.4 on 2018-05-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180512_1344'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0011_auto_20180520_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Tutor', verbose_name='tuteur')),
            ],
        ),
        migrations.RenameModel(
            old_name='VisitParticipant',
            new_name='Participation',
        ),
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'participation'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('date',), 'verbose_name': 'sortie'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='organizers',
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.ForeignKey(help_text='Adresse complète de ce lieu', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address', verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='visitorganizer',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visit', verbose_name='sortie'),
        ),
    ]
