# Generated by Django 2.0.4 on 2018-05-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0013_visit_organizers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorganizer',
            options={'verbose_name': 'organisateur'},
        ),
    ]
