# Generated by Django 2.0.4 on 2018-05-22 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0015_auto_20180520_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 39, 23, 229059), help_text='Heure de fin de la sortie. Format : hh:mm.', verbose_name='heure de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='meeting',
            field=models.CharField(blank=True, default='', help_text='Indiquez aux tutorés où ils devront vous retrouver. Exemple : "devant le musée".', max_length=100, verbose_name='lieu de rendez-vous'),
        ),
        migrations.AddField(
            model_name='visit',
            name='permission',
            field=models.FileField(blank=True, help_text='À mettre à disposition pour que le lycéen la remplisse. Tout format supporté, PDF recommandé.', null=True, upload_to='visits/visit_permissions/', verbose_name='autorisation de sortie'),
        ),
        migrations.AddField(
            model_name='visit',
            name='start_time',
            field=models.TimeField(default=datetime.time(21, 39, 32, 604487), help_text='Heure de début de la sortie. Format : hh:mm.', verbose_name='heure de début'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(help_text='Date de la sortie.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='deadline',
            field=models.DateTimeField(help_text="Note : les lycéens ne pourront plus s'inscrire passée cette date. Format de l'heure : hh:mm.", verbose_name="date limite d'inscription"),
        ),
        migrations.AlterField(
            model_name='visit',
            name='fact_sheet',
            field=models.FileField(blank=True, help_text='Informe le lycéen de détails sur la sortie. Tous formats supportés, PDF recommandé.', null=True, upload_to='visits/fact_sheets/', verbose_name='fiche sortie'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='image',
            field=models.ImageField(blank=True, help_text='Une illustration représentative de la sortie.', null=True, upload_to='visits/images/', verbose_name='illustration'),
        ),
    ]
