# Generated by Django 2.0.4 on 2018-05-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0016_auto_20180522_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachedfile',
            name='visit',
        ),
        migrations.DeleteModel(
            name='AttachedFile',
        ),
    ]
