# Generated by Django 2.0.4 on 2018-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0017_auto_20180522_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='accepted',
            field=models.NullBooleanField(help_text='Cocher pour confirmer au tutoré sa participation à la sortie.', verbose_name='accepté'),
        ),
    ]
