# Generated by Django 2.0.4 on 2018-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0018_auto_20180523_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'ordering': ('-submitted',), 'verbose_name': 'participation'},
        ),
        migrations.AddField(
            model_name='participation',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, help_text='Date de soumission de la participation', null=True, verbose_name='soumis le'),
        ),
    ]
