# Generated by Django 2.0.2 on 2018-03-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('slug', models.SlugField(help_text="Un identifiant unique pour ce lien. Privilégiez 'ce-format-de-slug'.", primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(help_text='Précisez ce que contient ce lien et comment il est utilisé.')),
            ],
            options={
                'verbose_name': 'lien',
            },
        ),
    ]
