# Generated by Django 2.0.3 on 2018-03-17 15:20

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'article", max_length=300, verbose_name='titre')),
                ('slug', models.SlugField(help_text="Un court identifiant généré après la création de l'article.", max_length=100, unique=True)),
                ('content', markdownx.models.MarkdownxField(help_text="Contenu complet de l'article", verbose_name='contenu')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='illustration')),
                ('pinned', models.BooleanField(default=False, verbose_name='épinglé')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='titre')),
            ],
            options={
                'verbose_name': 'catégorie',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='KeyFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure', models.PositiveIntegerField(help_text='Un nombre entier positif. Exemple : 60', verbose_name='chiffre')),
                ('description', models.CharField(help_text="Une courte description du chiffre (sera convertie en minuscules). Exemple : millions d'amis.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'chiffre clé',
                'verbose_name_plural': 'chiffres clés',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('website', models.URLField(null=True, verbose_name='site internet')),
                ('logo', models.ImageField(help_text='Image PNG avec arrière-plan transparent. Dimensions recommandées : hauteur = 320px. ', null=True, upload_to='')),
                ('premium', models.BooleanField(default=False, help_text='Cocher si ce partenaire est un partenaire privilégié. Il sera davantage mis en avant sur le site. Exemple : les organismes de subventions peuvent être des partenaires secondaires et les entreprises des partenaires principaux.', verbose_name='partenaire privilégié')),
                ('active', models.BooleanField(default=True, help_text='Cocher si le partenariat est actif. Les partenariats inactifs ne seront pas affichés sur le site.', verbose_name='actif')),
            ],
            options={
                'verbose_name': 'partenaire',
                'ordering': ('-active', '-premium', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
                ('author_name', models.CharField(help_text="Nom de l'auteur", max_length=300, verbose_name='auteur')),
                ('author_position', models.CharField(help_text="Position de l'auteur (lycéen, professeur…)", max_length=300, verbose_name='position')),
                ('created', models.DateField(auto_now_add=True, verbose_name='date de création')),
            ],
            options={
                'verbose_name': 'témoignage',
                'ordering': ('-created', 'author_name'),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Catégories auxquelles rattacher l'article", to='showcase_site.Category', verbose_name='catégories'),
        ),
    ]
