# Generated by Django 2.0.2 on 2018-02-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='titre')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField(verbose_name='contenu')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='date de publication')),
                ('image', models.ImageField(upload_to='')),
                ('pinned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ('-published',),
            },
        ),
    ]
