# Generated by Django 2.0.3 on 2018-03-19 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-active', '-premium', '-start_date', 'name'), 'verbose_name': 'partenaire'},
        ),
        migrations.AddField(
            model_name='partner',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text="Quand ce partenariat a-t-il débuté ? Cette information est stockée à des fins d'historiques.", verbose_name='début du partenariat'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='illustration'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(help_text='Image PNG avec arrière-plan transparent. Dimensions recommandées : hauteur = 320px. ', null=True, upload_to='partners/'),
        ),
    ]
