# Generated by Django 2.0.2 on 2018-02-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='illustration'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='épinglé'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now=True, verbose_name='date de publication'),
        ),
    ]
