# Generated by Django 2.0.3 on 2018-03-19 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0002_auto_20180319_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Laisser vide si inconnu. (Cette information est stockée pour historique uniquement.)', null=True, verbose_name='début du partenariat'),
        ),
    ]
