# Generated by Django 2.0.2 on 2018-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0002_auto_20180215_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de publication'),
        ),
    ]
