# Generated by Django 2.0.3 on 2018-03-25 12:42

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0004_auto_20180325_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='titre')),
                ('thumbnail', models.ImageField(blank=True, help_text="Une petite image représentant l'action. Format recommandé : 200x200", null=True, upload_to='actions/', verbose_name='illustration')),
                ('description', markdownx.models.MarkdownxField()),
                ('key_figure', models.TextField(blank=True, default='', help_text="Enoncer un chiffre clé à propos de cette action. Exemple : 'En 2018, 18 sorties ont été organisées dans des lieux tels que…'", verbose_name='chiffre clé')),
                ('highlight', models.BooleanField(default=True, help_text="Cochez pour afficher cette action sur la page d'accueil. Pour un affichage optimal, assurez-vous alors d'avoir renseigné une illustration.", verbose_name='mettre en avant')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'action clé',
                'verbose_name_plural': 'actions clés',
                'ordering': ('order',),
            },
        ),
    ]
