# Generated by Django 2.0.3 on 2018-04-07 10:51

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0005_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=markdownx.models.MarkdownxField(help_text="Un texte libre décrivant le point d'action. Markdown est supporté."),
        ),
    ]
