# Generated by Django 2.0.3 on 2018-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0006_auto_20180407_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'ordering': ('-created', 'source'), 'verbose_name': 'témoignage'},
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='author_position',
        ),
        migrations.RemoveField(
            model_name='testimony',
            name='content',
        ),
        migrations.AddField(
            model_name='testimony',
            name='quote',
            field=models.TextField(default='', verbose_name='citation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimony',
            name='source',
            field=models.CharField(default='', help_text="Nom et qualité de l'auteur ou de la source de ce témoignage.", max_length=300, verbose_name='source'),
            preserve_default=False,
        ),
    ]
