# Generated by Django 2.0.3 on 2018-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0007_auto_20180408_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='ajouté le'),
        ),
    ]
