# Generated by Django 2.0.3 on 2018-04-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0008_auto_20180408_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display_image',
            field=models.BooleanField(default=True, help_text="Cocher pour que l'illustration soit affichée sous le chapeau introductif de l'article.", verbose_name="afficher l'illustration"),
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text="Date et heure de la dernière modification de l'article", verbose_name='modifié le'),
        ),
    ]
