# Generated by Django 2.0.3 on 2018-04-11 21:28

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0009_auto_20180411_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('archived', '-pinned', '-published'), 'verbose_name': 'article'},
        ),
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False, help_text="Cocher pour que l'article soit archivé. Il ne sera plus affiché sur le site.", verbose_name='archivé'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(help_text="Contenu complet de l'article (Markdown est supporté).", verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modifié le'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pinned',
            field=models.BooleanField(default=False, help_text="Cocher pour que l'article soit épinglé et affiché en priorité.", verbose_name='épinglé'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='publié le'),
        ),
    ]
