# Generated by Django 2.0.7 on 2018-09-11 17:38

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'lycéen',
            },
            bases=(profiles.models.ProfileMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.IntegerField(choices=[(2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017')], default=2021)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor', to='core.Address', verbose_name='adresse')),
            ],
            options={
                'verbose_name': 'tuteur',
            },
            bases=(profiles.models.ProfileMixin, models.Model),
        ),
    ]
