# Generated by Django 2.2 on 2020-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200914_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dependantsNumber',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name="numéro d'urgence"),
        ),
        migrations.AlterField(
            model_name='student',
            name='fatherActivity',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='métier du père'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='niveau de la classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='motherActivity',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='métier de la mère'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.NullBooleanField(verbose_name='boursier'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name="nom de l'école"),
        ),
    ]
