# Generated by Django 2.2 on 2020-09-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200918_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='boursier'),
        ),
    ]
