# Generated by Django 2.2 on 2020-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200918_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='nationalité'),
        ),
        migrations.AddField(
            model_name='student',
            name='specialTeaching',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='enseignement de spécialité'),
        ),
        migrations.AddField(
            model_name='student',
            name='zipCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='code postal'),
        ),
    ]
