# Generated by Django 2.2 on 2020-09-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200918_1818'),
        ('profiles', '0004_auto_20200915_1827'),
    ]

    operations = [
    ]
