# Generated by Django 2.2 on 2020-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200918_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dependantsNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='nombre de personnes à charge'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nationalité'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentsEmail',
            field=models.EmailField(blank=True, max_length=70, null=True, verbose_name='adresse mail parentale'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parentsStatus',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='statut des parents'),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='boursier'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialTeaching',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='enseignement de spécialité'),
        ),
    ]
