# Generated by Django 2.2 on 2020-09-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200923_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='personnalPhone',
            new_name='personalPhone',
        ),
    ]
