# Generated by Django 2.2 on 2020-09-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200918_1921'),
        ('profiles', '0009_auto_20200923_1329'),
    ]

    operations = [
    ]
