# Generated by Django 2.2 on 2020-09-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_merge_20200923_1355'),
        ('profiles', '0010_auto_20200923_1444'),
    ]

    operations = [
    ]
