# Generated by Django 2.2 on 2020-09-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200923_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='général/techno'),
        ),
    ]
