# Generated by Django 2.2 on 2020-09-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_student_year'),
        ('profiles', '0011_merge_20200923_1507'),
    ]

    operations = [
    ]
