# Generated by Django 2.2 on 2020-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_merge_20200925_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='établissement'),
        ),
    ]
