# Generated by Django 2.2 on 2022-03-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_student_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='promotion',
            field=models.IntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020')], default=2024),
        ),
    ]
