# Generated by Django 2.2 on 2022-03-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20220321_0135'),
        ('profiles', '0016_auto_20211225_1242'),
    ]

    operations = [
    ]
