# Generated by Django 2.0.7 on 2018-09-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dynamicforms', '0001_initial'),
        ('profiles', '0002_auto_20180911_1938'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='editionorganizer',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Edition', verbose_name='édition'),
        ),
        migrations.AddField(
            model_name='editionorganizer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AddField(
            model_name='editionform',
            name='edition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edition_form', to='projects.Edition', verbose_name='édition'),
        ),
        migrations.AddField(
            model_name='editionform',
            name='form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamicforms.Form', verbose_name="formulaire d'inscription"),
        ),
        migrations.AddField(
            model_name='editionform',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Tuteur/tutrice à qui envoyer les pièces justificatives. Son adresse doit être renseignée dans son profil.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Tutor', validators=[projects.models._validate_address_is_set], verbose_name='destinataire'),
        ),
        migrations.AddField(
            model_name='edition',
            name='organizers',
            field=models.ManyToManyField(through='projects.EditionOrganizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edition',
            name='project',
            field=models.ForeignKey(help_text='Le projet dont ceci est une édition.', on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='projects.Project', verbose_name='projet'),
        ),
    ]
