# Generated by Django 2.0.6 on 2018-06-15 21:23

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180606_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'get_latest_by': 'year', 'ordering': ('-year',), 'verbose_name': 'édition'},
        ),
        migrations.AlterField(
            model_name='edition',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Une description spécifique pour cette édition.'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.Edition', verbose_name='édition'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Une description générale du projet'),
        ),
    ]
