# Generated by Django 2.0.6 on 2018-06-15 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180616_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionform',
            name='edition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Edition', verbose_name='édition'),
        ),
    ]
