# Generated by Django 2.0.6 on 2018-06-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0014_auto_20180616_1812'),
        ('projects', '0006_auto_20180616_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_participation', to='dynamicforms.FormEntry'),
        ),
        migrations.AlterField(
            model_name='editionform',
            name='edition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edition_form', to='projects.Edition', verbose_name='édition'),
        ),
        migrations.AlterField(
            model_name='editionform',
            name='form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamicforms.Form', verbose_name="formulaire d'inscription"),
        ),
    ]
