# Generated by Django 2.0.6 on 2018-06-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180616_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='entry',
            field=models.OneToOneField(help_text="Réponses au formulaire d'inscription", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_participation', to='dynamicforms.FormEntry', verbose_name='entrée'),
        ),
    ]
