# Generated by Django 2.0.6 on 2018-06-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180616_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionorganizer',
            name='role',
            field=models.CharField(blank=True, default='', help_text='Exemple : responsable projet, responsable inscriptions…', max_length=100, verbose_name='rôle'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='entry',
            field=models.OneToOneField(help_text="Réponses au formulaire d'inscription", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_participation', to='dynamicforms.FormEntry', verbose_name='entrée'),
        ),
    ]
