version: '3'

# Create data volumes to be shared between Django and Nginx
volumes:
  static:
  media:
  data:

services:

  # Django web app on Gunicorn WSGI server
  gunicorn:
    restart: always
    build: ./oser-backend
    container_name: django_01
    volumes:
      - data:/oser-backend/
      # Mount static and media file volumes
      - static:/oser-backend/static
      - media:/oser-backend/media

  # Nginx server
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx_01
    ports:
      - 8000:8000
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - static:/static/
      - media:/media/
    depends_on:
      - gunicorn
