version: '3'

# Create data volumes to be shared between Django and Nginx
volumes:
  data:

services:

  # Django web app on Gunicorn WSGI server
  # Serves static files directly thanks to WhiteNoise
  gunicorn:
    restart: always
    build: ./oser-backend
    container_name: django_container
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      # Sync local project folder to container's, allowing
      # to see effects of code changes without need to rebuild image.
      - ./oser-backend/:/oser-backend/
    depends_on:
      # start db container before this one
      - db

  # PostgreSQL database
  db:
    # default username/password is postgres/postgres
    restart: always
    image: postgres:9.6
    container_name: postgres_container
    expose:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data/
