# Generated by Django 2.0.7 on 2018-09-11 17:38

from django.db import migrations, models
import django_countries.fields
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Numéro, voie, rue…', max_length=300, verbose_name='ligne 1')),
                ('line2', models.CharField(blank=True, default='', help_text='Résidence, appartement, lieu-dit…', max_length=300, verbose_name='ligne 2')),
                ('post_code', models.CharField(help_text="Code postal. Note : le format n'est pas vérifié.", max_length=20, verbose_name='code postal')),
                ('city', models.CharField(help_text='Ville', max_length=100, verbose_name='ville')),
                ('country', django_countries.fields.CountryField(default='FR', help_text='Pays (FR par défaut).', max_length=2, verbose_name='pays')),
            ],
            options={
                'verbose_name': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du document', max_length=300, verbose_name='titre')),
                ('slug', models.SlugField(help_text='Un court identifiant généré après la création du document.', max_length=100, unique=True)),
                ('content', markdownx.models.MarkdownxField(help_text='Contenu du document (Markdown est supporté).', verbose_name='contenu')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
