# Generated by Django 2.0.3 on 2018-03-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
