# Generated by Django 2.0.3 on 2018-03-24 18:37

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du document', max_length=300, verbose_name='titre')),
                ('slug', models.SlugField(help_text='Un court identifiant généré après la création du document.', max_length=100, unique=True)),
                ('content', markdownx.models.MarkdownxField(help_text='Contenu du document (Markdown est supporté).', verbose_name='contenu')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
