# Generated by Django 2.0.3 on 2018-04-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180407_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='téléphone'),
        ),
    ]
