# Generated by Django 2.0.3 on 2018-04-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180407_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-submitted',), 'verbose_name': "dossier d'inscription", 'verbose_name_plural': "dossiers d'inscription"},
        ),
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(help_text='Date de naissance du lycéen', null=True, verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(help_text='Adresse email personnelle du lycéen (doit être une adresse mail valide)', max_length=254, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(help_text='Prénom du lycéen (50 caractères max)', max_length=50, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(help_text='Nom du lycéen (50 caracèteres max)', max_length=50, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, help_text="Numéro de téléphone personnel du lycéen (30 caracètres max). Note : le format n'est pas vérifié.", max_length=30, null=True, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, help_text="Date d'envoi du dossier d'inscription", verbose_name='envoyé le'),
        ),
    ]
