# Generated by Django 2.0.3 on 2018-04-08 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20180408_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2018, 4, 8), help_text='Date de naissance du lycéen', verbose_name='date de naissance'),
            preserve_default=False,
        ),
    ]
