# Generated by Django 2.0.3 on 2018-04-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Adresse du lycéen', null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Address'),
        ),
        migrations.AddField(
            model_name='registration',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text="Contact en cas d'urgence Exemple : adresse mail ou numéro de téléphone d'un parent.", max_length=100, null=True, verbose_name="contact d'urgence"),
        ),
    ]
