# Generated by Django 2.0.3 on 2018-04-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20180408_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Adresse du lycéen', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
