# Generated by Django 2.0.3 on 2018-04-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20180414_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text='Prénom du contact (50 caractères max).', max_length=50, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text='Nom du contact (50 caractères max).', max_length=50, verbose_name='nom'),
        ),
    ]
