# Generated by Django 2.0.4 on 2018-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_auto_20180505_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='validated',
            field=models.BooleanField(default=False, help_text="Cocher pour valider le dossier d'inscription. Le lycéen pourra alors avoir accès à toutes les fonctionnalités associées à son profil.", verbose_name='validé'),
        ),
    ]
