# Generated by Django 2.0.4 on 2018-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20180512_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='level',
        ),
        migrations.AddField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, help_text='Classe/filière du lycéen (texte libre)', max_length=200, null=True),
        ),
    ]
