# Generated by Django 2.0.2 on 2018-03-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visitattachedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitattachedfile',
            name='file',
        ),
    ]
