# Generated by Django 2.0.6 on 2018-06-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0002_auto_20180615_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='entry',
            field=models.ForeignKey(help_text='Entrée associée à la réponse.', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dynamicforms.FormEntry', verbose_name='entrée'),
        ),
        migrations.AlterField(
            model_name='formentry',
            name='form',
            field=models.ForeignKey(help_text="Formulaire associé à l'entrée.", on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dynamicforms.Form', verbose_name='formulaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(help_text='Formulaire associé à la question.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dynamicforms.Form', verbose_name='formulaire'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=True, verbose_name='requis'),
        ),
    ]
