# Generated by Django 2.0.6 on 2018-06-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0003_auto_20180615_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='type',
        ),
    ]
