# Generated by Django 2.0.6 on 2018-06-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0004_auto_20180615_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, default='', help_text='Apporte des précisions sur la question', max_length=500, verbose_name='aide'),
        ),
    ]
