# Generated by Django 2.0.6 on 2018-06-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0006_auto_20180615_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text-small', 'Texte court'), ('text-small', 'Texte long'), ('date', 'Date'), ('sex', 'Sexe')], max_length=100, verbose_name='type de question'),
        ),
    ]
