# Generated by Django 2.0.6 on 2018-06-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0008_auto_20180616_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nom')),
                ('file', models.FileField(upload_to='forms/attachments/', verbose_name='fichier')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='dynamicforms.Form', verbose_name='formulaire')),
            ],
            options={
                'verbose_name': 'fichier',
                'verbose_name_plural': 'fichiers',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text-small', 'Texte court'), ('text-small', 'Texte long'), ('yes-no', 'Oui/Non'), ('date', 'Date'), ('sex', 'Sexe')], max_length=100, verbose_name='type de question'),
        ),
    ]
