# Generated by Django 2.0.6 on 2018-06-15 23:21

from django.db import migrations, models
import dynamicforms.utils


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0009_auto_20180616_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(default='noname', max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=dynamicforms.utils.file_upload_to, verbose_name='fichier'),
        ),
    ]
