# Generated by Django 2.0.6 on 2018-06-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0010_auto_20180616_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
