# Generated by Django 2.0.6 on 2018-06-15 23:45

from django.db import migrations, models
import django.db.models.deletion


def remove_questions_with_null_sections(apps, schema_editor):
    Question = apps.get_model('dynamicforms', 'Question')
    Question.objects.filter(section__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0011_auto_20180616_0141'),
    ]

    operations = [
        migrations.RunPython(remove_questions_with_null_sections),
    ]
