# Generated by Django 2.0.3 on 2018-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='adresse email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='téléphone')),
                ('date_of_birth', models.DateField(null=True, verbose_name='date de naissance')),
                ('submitted', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
            ],
            options={
                'ordering': ('-submitted',),
            },
        ),
    ]
