# Generated by Django 2.0.7 on 2018-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Prénom du lycéen (50 caractères max)', max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(help_text='Nom du lycéen (50 caracèteres max)', max_length=50, verbose_name='nom')),
                ('email', models.EmailField(help_text='Adresse email personnelle du lycéen. Note : doit être une adresse mail valide.', max_length=254, verbose_name='adresse email')),
                ('submitted', models.DateTimeField(auto_now_add=True, help_text="Date d'envoi du dossier d'inscription", verbose_name='envoyé le')),
                ('validated', models.BooleanField(default=False, help_text="Cocher pour valider le dossier d'inscription. Le lycéen pourra alors avoir accès à toutes les fonctionnalités associées à son profil.", verbose_name='validé')),
            ],
            options={
                'verbose_name': "dossier d'inscription",
                'verbose_name_plural': "dossiers d'inscription",
                'ordering': ('-submitted',),
            },
        ),
    ]
