# Generated by Django 2.0.3 on 2018-04-08 12:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180408_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(help_text='Numéro, voie, rue…', max_length=300, verbose_name='ligne 1')),
                ('line2', models.CharField(blank=True, default='', help_text='Résidence, appartement, lieu-dit…', max_length=300, verbose_name='ligne 2')),
                ('post_code', models.CharField(help_text="Code postal. Note : le format n'est pas vérifié.", max_length=20, verbose_name='code postal')),
                ('city', models.CharField(help_text='Ville', max_length=100, verbose_name='ville')),
                ('country', django_countries.fields.CountryField(default='FR', help_text='Pays (FR par défaut).', max_length=2)),
            ],
        ),
    ]
