# Generated by Django 2.0.3 on 2018-04-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20180408_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Adresse du lycéen', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address', verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(help_text='Adresse email personnelle du lycéen. Note : doit être une adresse mail valide.', max_length=254, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text="Contact en cas d'urgence (100 caractères max). Exemple : adresse mail ou numéro de téléphone d'un parent.", max_length=100, null=True, verbose_name="contact d'urgence"),
        ),
    ]
