# Generated by Django 2.0.3 on 2018-04-13 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180414_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='emergency_contact',
            field=models.OneToOneField(blank=True, help_text="Contact en cas d'urgence.", null=True, on_delete=django.db.models.deletion.CASCADE, to='register.EmergencyContact', verbose_name="contact d'urgence"),
        ),
    ]
