# Generated by Django 2.0.4 on 2018-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20180414_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='contact',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='adresse email'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='home_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='téléphone fixe'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='téléphone portable'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='first_name',
            field=models.CharField(help_text='Prénom du contact (50 caractères max).', max_length=50, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='last_name',
            field=models.CharField(help_text='Nom du contact (50 caractères max).', max_length=50, verbose_name='nom'),
        ),
    ]
