# Generated by Django 2.0.4 on 2018-05-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_registration_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date de naissance du lycéen', null=True, verbose_name='date de naissance'),
        ),
    ]
