# Generated by Django 2.0.4 on 2018-05-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_auto_20180429_1159'),
        ('register', '0015_auto_20180505_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='level',
            field=models.CharField(blank=True, help_text='Classe du lycée (texte libre)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Lycée du lycéen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring.School', verbose_name='lycée'),
        ),
    ]
