# Generated by Django 2.0.4 on 2018-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_auto_20180512_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, help_text='Classe/filière du lycéen (texte libre)', max_length=200, null=True, verbose_name='classe'),
        ),
    ]
