# Generated by Django 2.0.2 on 2018-03-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('website', models.URLField(blank=True, verbose_name='site internet')),
                ('logo', models.ImageField(upload_to='')),
                ('first_class', models.BooleanField(default=False, help_text='Cocher si ce partenaire est un partenaire privilégié. Il sera davantage mis en avant sur le site. Exemple : les organismes de subventions peuvent être des partenaires secondaires et les entreprises des partenaires principaux.', verbose_name='partenaire principal')),
            ],
            options={
                'verbose_name': 'partenaire',
                'ordering': ('name',),
            },
        ),
    ]
