# Generated by Django 2.0.2 on 2018-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0002_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='first_class',
        ),
        migrations.AddField(
            model_name='partner',
            name='premium',
            field=models.BooleanField(default=False, help_text='Cocher si ce partenaire est un partenaire privilégié. Il sera davantage mis en avant sur le site. Exemple : les organismes de subventions peuvent être des partenaires secondaires et les entreprises des partenaires principaux.', verbose_name='partenaire privilégié'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(help_text='Image PNG avec arrière-plan transparent. Dimensions recommandées : hauteur = 320px. ', upload_to=''),
        ),
    ]
