# Generated by Django 2.0.2 on 2018-03-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0003_auto_20180304_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(help_text='Image PNG avec arrière-plan transparent. Dimensions recommandées : hauteur = 320px. ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(null=True, verbose_name='site internet'),
        ),
    ]
