# Generated by Django 2.0.2 on 2018-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0004_auto_20180304_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True, help_text='Cocher si le partenariat est actif. Les partenariats inactifs ne seront pas affichés sur le site.', verbose_name='actif'),
        ),
    ]
