# Generated by Django 2.0.2 on 2018-03-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showcase_site', '0005_partner_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-active', '-premium', 'name'), 'verbose_name': 'partenaire'},
        ),
    ]
