# Generated by Django 2.0.4 on 2018-05-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0010_auto_20180520_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.ForeignKey(help_text='Adresse complète de ce lieu', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Address'),
        ),
    ]
