# Generated by Django 2.0.3 on 2018-04-08 13:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adresse'},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='FR', help_text='Pays (FR par défaut).', max_length=2, verbose_name='pays'),
        ),
    ]
