# Generated by Django 2.0 on 2017-12-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('student', 'Lycéen'), ('tutor', 'Tuteur'), ('schoolstaffmember', 'Membre du personnel de lycée')], max_length=20, null=True, verbose_name='type de profil'),
        ),
    ]
