# Generated by Django 2.0.4 on 2018-04-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0002_auto_20180421_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.OneToOneField(help_text='Adresse complète du lycée', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address', verbose_name='adresse'),
        ),
    ]
