# Generated by Django 2.0.4 on 2018-04-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_auto_20180429_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='tutoring_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutoring.TutoringGroup', verbose_name='groupe de tutorat'),
        ),
    ]
