# Generated by Django 2.0.4 on 2018-05-12 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tutoring', '0004_auto_20180429_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringgroup',
            name='tutors',
            field=models.ManyToManyField(blank=True, null=True, related_name='tutoring_groups', through='tutoring.TutorTutoringGroup', to='profiles.Tutor', verbose_name='tuteurs'),
        ),
        migrations.AddField(
            model_name='tutortutoringgroup',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Tutor', verbose_name='Tuteur'),
        ),
    ]
