# Generated by Django 2.0.4 on 2018-05-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_auto_20180512_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringgroup',
            name='tutors',
            field=models.ManyToManyField(blank=True, related_name='tutoring_groups', through='tutoring.TutorTutoringGroup', to='profiles.Tutor', verbose_name='tuteurs'),
        ),
        migrations.AlterField(
            model_name='tutortutoringgroup',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Tutor', verbose_name='Tuteur'),
        ),
    ]
